apiVersion: v1
kind: Pod
metadata:
   name: pod-volume-config
spec:
   containers:
     - name:  test-container
       image: busybox
       command:  [ "/bin/sh", "-c", "--"]
       args:  ["while true; do sleep 30; done;"]
       volumeMounts:
       - name: config-volume
         mountPath: /etc/config
       imagePullPolicy: IfNotPresent
   volumes:
     - name: config-volume
       configMap:
         name: log-config
   restartPolicy: Never